#!/bin/bash

# Simple script to create folder tree really fast.

# Uncomment if u want to write number manually:
# echo ''
# echo "Enter the number of month (like 05, 12, or something) : "
# read month

month=`date +%m`

mkdir -p {01..04}_week_$month/{source,end,txt/{Vedomosti,TMT,Other}/done}

echo 
echo -e '\033[0;32mdone!'
echo 
